Repository ManageIQ/log_decorator, pull requests merged in 2020-05, with the labels that each got.

#9 Fix specs by requiring stringio
  .travis.yml
  spec/spec_helper.rb
Labels: bug, test

#10 Removing deprecated Gemnasium badge
  .codeclimate.yml
  README.md
Labels: developer

#11 Update rake dependency to address CVE-2020-8130
  log_decorator.gemspec
Labels: bug, developer
